print("****************************************************")
print("Hello, I am Ajaya Kandel.")
print("I am 32 years old.")
print("Currently, I live in Japan.")
print("My ambition is to become a programmer in the future.")
print("I have also learned Flutter with Bisowraj Sir.")
print("Additionally, I want to learn Python and understand backend development.")
print("In the future, I aim to build my own IT company in Japan.")
print("I plan to acquire many IT projects from Japanese companies" )
print("And share those projects in Nepal.This will enable many Nepali IT engineers to work in Nepal.")
print("Thank you to everyone. I am delighted to have the opportunity to learn Python with all of you.")
print("****************************************************")